### PR TITLE
Some bug fixes and improvments

### PR DESCRIPTION
**Pull request by k1-hedayati**

### CODE REVIEW

**Comment by tuhdo** [comment]
Batsov has [just taken over Grizzl](https://twitter.com/bbatsov/status/555262136348585984), so I doubt it will be removed.

**Comment by k1-hedayati** [comment]
I've rebased commits, thier hash changed, comments are removed, funny. Original commits:
341fd987055f319860267e35a34191f239dbd407 Added magit-filenotify
642a92ad5138655b00d8dd64cd527513fea54341 Moved elisp-slime-nav to elisp module
21d6f7e768d7417ec3d589d61dfcaaaf916b1250 Removed rainbow-mode from prelude-packages
82d2d9cbdd5760dc23676f51ed8728937d6bac4a Removed redundant command

**Comment by andrebeat** [comment]
Adding the `magit-filenotify` dependency breaks `magit` on OSX. The file notify API doesn't work on OS X and when you try to open a `magit` buffer you get the following error `file-notify-add-watch: No file notification package available`.

**Comment by k1-hedayati** [comment]
@andrebeat `magit-filenotify` removed in #791

**Pull request merged**
