### PR TITLE
add stylus-mode auto installation

### PR DESCRIPTION
**Pull request by CNBorn**

### CODE REVIEW

**Comment by bbatsov** [comment]
Where's the repo for this mode?

**Comment by CNBorn** [comment]
I think is https://github.com/brianc/jade-mode

[reference](https://github.com/milkypostman/melpa/blob/master/recipes/stylus-mode)

also on MELPA
```
    stylus-mode is an available package.

    Status: Available from melpa -- Install
    Archive: melpa
    Version: 20150313.812
    Requires: sws-mode-0
    Summary: Major mode for editing .jade files
    Homepage: https://github.com/brianc/jade-mode

```

**Comment by bbatsov** [comment]
Ok, just capitalise the commit message.

**Comment by CNBorn** [comment]
@bbatsov Thanks, updated

**Pull request merged**
