### PR TITLE
Add cheatsheet

### LINKED ISSUE #1142: Anybody have a Prelude Cheat Sheet ?
(In the README)
It would be really cool if we can have/link-to an updated version of this
with all the prelude (shortcut) goodies included

rxlwp

### PR DESCRIPTION
**Pull request by zzhjerry**
This PR adds a cheatsheet of keybindings defined (or overwritten) by Prelude. Some particularly useful keybindings not defined by Prelude but by packages used in Prelude are also listed (e.g. `flycheck` and `projectile`). 

Please let me know if anything needs to be changed and I'm happy to make modifications.

image

Closes #1142

### CODE REVIEW

**Comment by bbatsov** [comment]
Great work!

I guess you should mention it in the README and probably add some instructions about generating the pdf version.

**Comment by zzhjerry** [comment]
Updated. 

Included a screenshot and updated README as well as the documentation of generating pdf version

**Comment by zzhjerry** [comment]
The latest update also added cheatsheet in TOC

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
